# Generated by Django 4.2.7 on 2023-12-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_hub', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='-', max_length=2083),
        ),
    ]
