# Generated by Django 4.2.7 on 2023-12-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_hub', '0006_engineer_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='-'),
        ),
    ]
