# Generated by Django 4.2.7 on 2023-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_hub', '0007_alter_article_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='-', editable=False),
        ),
    ]
