# Generated by Django 4.2.7 on 2023-12-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_hub', '0009_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at_date',
            field=models.DateField(default='2023-12-05', editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at_date',
            field=models.DateTimeField(default='2023-12-05', editable=False),
        ),
    ]
