# Generated by Django 4.2.7 on 2024-01-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_hub', '0017_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='\n<section>\n        <h4>[Title 1]</h4>\n        <p>[Description 1]</p>\n    </section>\n    \n    <section>\n        <h4>[Title 2]</h4>\n        <p>[Description 2]</p>\n    </section>\n    \n    <section>\n        <h4>[Title 3]</h4>\n        <p>[Description 3]</p>\n    </section>\n    \n    <section>\n        <h4>[Title 4]</h4>\n        <p>[Description 4]</p>\n    </section>\n    \n    <section>\n        <h4>[Title 5]</h4>\n        <p>[Description 5]</p>\n    </section>\n    \n    <section>\n        <h4>[Title 6]</h4>\n        <p>[Description 6]</p>\n    </section>\n    \n    <section>\n        <h4>[Title 7]</h4>\n        <p>[Description 7]</p>\n    </section>\n    \n    <section>\n        <h4>[Title 8]</h4>\n        <p>[Description 8]</p>\n    </section>\n    \n    <section>\n        <p>[Conclusion]</p>\n    </section>\n', max_length=10000),
        ),
    ]
